# Generated by Django 5.1.11 on 2025-07-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titel',
            new_name='title',
        ),
    ]
